using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.NameIdentifier;
using Content.Shared.Preferences;
using Content.Shared.Silicons.Borgs;
using Content.Shared.Silicons.Borgs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Silicons.Borgs;

[GenerateTypedNameReferences]
public sealed partial class IPCMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public Action? EjectBatteryButtonPressed;
    public Action<EntityUid>? RemoveModuleButtonPressed;

    public float AccumulatedTime;
    private List<EntityUid> _modules = new();

    public EntityUid Entity;

    public IPCMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        EjectBatteryButton.OnPressed += _ => EjectBatteryButtonPressed?.Invoke();

    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
        BorgSprite.SetEntity(entity);

    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        AccumulatedTime += args.DeltaSeconds;
        BorgSprite.OverrideDirection = (Direction)((int)AccumulatedTime % 4 * 2);
    }

    public void UpdateState(BorgBuiState state)
    {
        EjectBatteryButton.Disabled = !state.HasBattery;
        ChargeBar.Value = state.ChargePercent;
        ChargeLabel.Text = Loc.GetString("borg-ui-charge-label",
            ("charge", (int)MathF.Round(state.ChargePercent * 100)));

        UpdateModulePanel();
    }

    private void UpdateModulePanel()
    {
        if (!_entity.TryGetComponent(Entity, out BorgChassisComponent? chassis))
            return;

        ModuleCounter.Text = Loc.GetString("borg-ui-module-counter",
            ("actual", chassis.ModuleCount),
            ("max", chassis.MaxModules));

        if (chassis.ModuleContainer.Count == _modules.Count)
        {
            var isSame = true;
            foreach (var module in chassis.ModuleContainer.ContainedEntities)
            {
                if (_modules.Contains(module))
                    continue;
                isSame = false;
                break;
            }

            if (isSame)
                return;
        }

        ModuleContainer.Children.Clear();
        _modules.Clear();
        foreach (var module in chassis.ModuleContainer.ContainedEntities)
        {
            var moduleComponent = _entity.GetComponent<BorgModuleComponent>(module);
            var control = new BorgModuleControl(module, _entity, true); // Mono - can remove even if default
            control.RemoveButtonPressed += () =>
            {
                RemoveModuleButtonPressed?.Invoke(module);
            };
            ModuleContainer.AddChild(control);
            _modules.Add(module);
        }
    }
}
